---
abstract: 'Build your development environment by perl-based DSL'
author:
  - 'magnolia <magnolia.k@me.com>'
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3603'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Enbld
provides:
  Enbld:
    file: lib/Enbld.pm
    version: 0.7008
  Enbld::App:
    file: lib/Enbld/App.pm
  Enbld::App::Configuration:
    file: lib/Enbld/App/Configuration.pm
  Enbld::Archivefile:
    file: lib/Enbld/Archivefile.pm
  Enbld::Catchme:
    file: lib/Enbld/Catchme.pm
  Enbld::Command:
    file: lib/Enbld/Command.pm
  Enbld::Command::Available:
    file: lib/Enbld/Command/Available.pm
  Enbld::Command::Deploy:
    file: lib/Enbld/Command/Deploy.pm
  Enbld::Command::Freeze:
    file: lib/Enbld/Command/Freeze.pm
  Enbld::Command::Help:
    file: lib/Enbld/Command/Help.pm
  Enbld::Command::Install:
    file: lib/Enbld/Command/Install.pm
  Enbld::Command::List:
    file: lib/Enbld/Command/List.pm
  Enbld::Command::Off:
    file: lib/Enbld/Command/Off.pm
  Enbld::Command::Outdated:
    file: lib/Enbld/Command/Outdated.pm
  Enbld::Command::Rehash:
    file: lib/Enbld/Command/Rehash.pm
  Enbld::Command::Upgrade:
    file: lib/Enbld/Command/Upgrade.pm
  Enbld::Command::Usage:
    file: lib/Enbld/Command/Usage.pm
  Enbld::Command::Use:
    file: lib/Enbld/Command/Use.pm
  Enbld::Command::Version:
    file: lib/Enbld/Command/Version.pm
  Enbld::Condition:
    file: lib/Enbld/Condition.pm
  Enbld::Config:
    file: lib/Enbld/Config.pm
  Enbld::Copy:
    file: lib/Enbld/Copy.pm
  Enbld::Definition:
    file: lib/Enbld/Definition.pm
  Enbld::Definition::Apache:
    file: lib/Enbld/Definition/Apache.pm
  Enbld::Definition::Apr:
    file: lib/Enbld/Definition/Apr.pm
  Enbld::Definition::Aprutil:
    file: lib/Enbld/Definition/Aprutil.pm
  Enbld::Definition::Autoconf:
    file: lib/Enbld/Definition/Autoconf.pm
  Enbld::Definition::Automake:
    file: lib/Enbld/Definition/Automake.pm
  Enbld::Definition::Cmake:
    file: lib/Enbld/Definition/Cmake.pm
  Enbld::Definition::Emacs:
    file: lib/Enbld/Definition/Emacs.pm
  Enbld::Definition::Git:
    file: lib/Enbld/Definition/Git.pm
  Enbld::Definition::Groff:
    file: lib/Enbld/Definition/Groff.pm
  Enbld::Definition::Hello:
    file: lib/Enbld/Definition/Hello.pm
  Enbld::Definition::Libevent:
    file: lib/Enbld/Definition/Libevent.pm
  Enbld::Definition::Libidn:
    file: lib/Enbld/Definition/Libidn.pm
  Enbld::Definition::Libtool:
    file: lib/Enbld/Definition/Libtool.pm
  Enbld::Definition::Mysql:
    file: lib/Enbld/Definition/Mysql.pm
  Enbld::Definition::Nginx:
    file: lib/Enbld/Definition/Nginx.pm
  Enbld::Definition::Nodejs:
    file: lib/Enbld/Definition/Nodejs.pm
  Enbld::Definition::Pcre:
    file: lib/Enbld/Definition/Pcre.pm
  Enbld::Definition::Perl:
    file: lib/Enbld/Definition/Perl.pm
  Enbld::Definition::Pkgconfig:
    file: lib/Enbld/Definition/Pkgconfig.pm
  Enbld::Definition::Python:
    file: lib/Enbld/Definition/Python.pm
  Enbld::Definition::Rakudostar:
    file: lib/Enbld/Definition/Rakudostar.pm
  Enbld::Definition::Ruby:
    file: lib/Enbld/Definition/Ruby.pm
  Enbld::Definition::Scala:
    file: lib/Enbld/Definition/Scala.pm
  Enbld::Definition::Tmux:
    file: lib/Enbld/Definition/Tmux.pm
  Enbld::Definition::Tree:
    file: lib/Enbld/Definition/Tree.pm
  Enbld::Definition::Vim:
    file: lib/Enbld/Definition/Vim.pm
  Enbld::Definition::Wget:
    file: lib/Enbld/Definition/Wget.pm
  Enbld::Definition::Zsh:
    file: lib/Enbld/Definition/Zsh.pm
  Enbld::Deployed:
    file: lib/Enbld/Deployed.pm
  Enbld::Error:
    file: lib/Enbld/Error.pm
  Enbld::Exception:
    file: lib/Enbld/Exception.pm
  Enbld::Feature:
    file: lib/Enbld/Feature.pm
  Enbld::HTML:
    file: lib/Enbld/HTML.pm
  Enbld::HTTP:
    file: lib/Enbld/HTTP.pm
  Enbld::Home:
    file: lib/Enbld/Home.pm
  Enbld::Logger:
    file: lib/Enbld/Logger.pm
  Enbld::Message:
    file: lib/Enbld/Message.pm
  Enbld::Module:
    file: lib/Enbld/Module.pm
  Enbld::Module::Perl:
    file: lib/Enbld/Module/Perl.pm
  Enbld::RcFile:
    file: lib/Enbld/RcFile.pm
  Enbld::Target:
    file: lib/Enbld/Target.pm
  Enbld::Target::Attribute:
    file: lib/Enbld/Target/Attribute.pm
  Enbld::Target::Attribute::AdditionalArgument:
    file: lib/Enbld/Target/Attribute/AdditionalArgument.pm
  Enbld::Target::Attribute::AllowedCondition:
    file: lib/Enbld/Target/Attribute/AllowedCondition.pm
  Enbld::Target::Attribute::ArchiveName:
    file: lib/Enbld/Target/Attribute/ArchiveName.pm
  Enbld::Target::Attribute::CommandConfigure:
    file: lib/Enbld/Target/Attribute/CommandConfigure.pm
  Enbld::Target::Attribute::CommandInstall:
    file: lib/Enbld/Target/Attribute/CommandInstall.pm
  Enbld::Target::Attribute::CommandMake:
    file: lib/Enbld/Target/Attribute/CommandMake.pm
  Enbld::Target::Attribute::CommandTest:
    file: lib/Enbld/Target/Attribute/CommandTest.pm
  Enbld::Target::Attribute::CopyFiles:
    file: lib/Enbld/Target/Attribute/CopyFiles.pm
  Enbld::Target::Attribute::Dependencies:
    file: lib/Enbld/Target/Attribute/Dependencies.pm
  Enbld::Target::Attribute::DistName:
    file: lib/Enbld/Target/Attribute/DistName.pm
  Enbld::Target::Attribute::DownloadSite:
    file: lib/Enbld/Target/Attribute/DownloadSite.pm
  Enbld::Target::Attribute::Extension:
    file: lib/Enbld/Target/Attribute/Extension.pm
  Enbld::Target::Attribute::Filename:
    file: lib/Enbld/Target/Attribute/Filename.pm
  Enbld::Target::Attribute::IndexParserForm:
    file: lib/Enbld/Target/Attribute/IndexParserForm.pm
  Enbld::Target::Attribute::IndexSite:
    file: lib/Enbld/Target/Attribute/IndexSite.pm
  Enbld::Target::Attribute::PatchFiles:
    file: lib/Enbld/Target/Attribute/PatchFiles.pm
  Enbld::Target::Attribute::Prefix:
    file: lib/Enbld/Target/Attribute/Prefix.pm
  Enbld::Target::Attribute::SortedVersionList:
    file: lib/Enbld/Target/Attribute/SortedVersionList.pm
  Enbld::Target::Attribute::URL:
    file: lib/Enbld/Target/Attribute/URL.pm
  Enbld::Target::Attribute::Version:
    file: lib/Enbld/Target/Attribute/Version.pm
  Enbld::Target::Attribute::VersionCondition:
    file: lib/Enbld/Target/Attribute/VersionCondition.pm
  Enbld::Target::Attribute::VersionForm:
    file: lib/Enbld/Target/Attribute/VersionForm.pm
  Enbld::Target::Attribute::VersionList:
    file: lib/Enbld/Target/Attribute/VersionList.pm
  Enbld::Target::Attribute::WebSite:
    file: lib/Enbld/Target/Attribute/WebSite.pm
  Enbld::Target::AttributeCollector:
    file: lib/Enbld/Target/AttributeCollector.pm
  Enbld::Target::AttributeExtension::Command:
    file: lib/Enbld/Target/AttributeExtension/Command.pm
  Enbld::Target::AttributeExtension::RegEx:
    file: lib/Enbld/Target/AttributeExtension/RegEx.pm
  Enbld::Target::AttributeExtension::URL:
    file: lib/Enbld/Target/AttributeExtension/URL.pm
  Enbld::Target::AttributeExtension::Word:
    file: lib/Enbld/Target/AttributeExtension/Word.pm
  Enbld::Target::Symlink:
    file: lib/Enbld/Target/Symlink.pm
  Enbld::Tutorial:
    file: lib/Enbld/Tutorial.pm
  Test::Enbld::Definition:
    file: lib/Test/Enbld/Definition.pm
requires:
  perl: 5.012
resources:
  license: http://dev.perl.org/licenses/
version: 0.7008
