---
abstract: 'Yet another package manager for building development environment'
author:
  - 'magnolia <magnolia.k@me.com>'
build_requires: {}
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Enbld
no_index:
  directory:
    - t
    - inc
    - xt
resources:
  bugtracker: https://github.com/magnolia-k/Enbld/issues
  homepage: https://github.com/magnolia-k/Enbld
  repository: https://github.com/magnolia-k/Enbld.git
version: 0.7037
